Makalem/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Makalem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Makalem.Controllers
{
    public class AdminController : Controller
    {
        MakaleAraBulContext mabc = new MakaleAraBulContext();
        public IActionResult Index(Kullanici giris)
        {
            if (HttpContext.Session.GetString("KullaniciType") != "2")
            {
                return RedirectToAction("Index", "Home");
            }

            return View(giris);
        }

        public IActionResult Comment(int id, int cid)
        {
            Yorum cmt = mabc.Yorum.FirstOrDefault(İ => İ.Id == id);
            if (cid == 1)
            {
                mabc.Yorum.Remove(cmt);
                mabc.SaveChanges();

            }
            else if (cid == 2)
            {
                cmt.DurumTipi = true;
                mabc.Yorum.Update(cmt);
                mabc.SaveChanges();
            }

            IEnumerable<Yorum> com = mabc.Yorum;
            return View(com);
        }

        public IActionResult Usr(int id, byte type)
        {
            Kullanici kln = mabc.Kullanici.FirstOrDefault(i => i.Id == id);
            if (type == 0 && id != 0)
            {
                mabc.Kullanici.Remove(kln);
                mabc.SaveChanges();

            }
            else if (type == 2 || type == 1)
            {
                kln.KullaniciTipi = type;
                mabc.Kullanici.Update(kln);
                mabc.SaveChanges();
            }
            IEnumerable<Kullanici> klnc = mabc.Kullanici;
            return View(klnc);
        }

        public IActionResult Article(int id, int cid)
        {
            Makale mak = mabc.Makale.FirstOrDefault(i => i.Id == id);

            if (cid != 0)
            {
                mak.DurumTipi = true;
                mabc.Makale.Update(mak);
                mabc.SaveChanges();

            }
            else if (id != 0 )
            {
                IEnumerable<MakaleKategori> makcat = mabc.MakaleKategori.Where(i => i.MakaleId == id);
                mabc.RemoveRange(makcat);
                mabc.SaveChanges();

                IEnumerable<Yorum> makyor = mabc.Yorum.Where(i => i.MakaleId == id);
                mabc.RemoveRange(makyor);
                mabc.SaveChanges();

                mabc.Remove(mak);
                mabc.SaveChanges();
            }
            

            return View(mabc.Makale);
        }
    }
}

Makalem/Controllers/MakaleEkleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Makalem.Models;
using Microsoft.AspNetCore.Http;

namespace Makalem.Controllers
{
    public class MakaleEkleController : Controller
    {
        MakaleAraBulContext mb = new MakaleAraBulContext();
        public IActionResult MakaleEkle()
        {
            if (HttpContext.Session.GetString("KullaniciType") == "0")
            {
                return RedirectToAction("Index", "Home");
            }

            IEnumerable<Kategori> k = mb.Kategori;
            return View(k);
        }
        [HttpPost]
        public IActionResult MakaleEkle(string Baslik, string Icerik, int MakaleDili, List<int> catid)
        {
            Makale m = new Makale();
            m.Baslik = Baslik;
            m.Icerik = Icerik;
            m.OlusturulanKullaniciId = Convert.ToInt32(HttpContext.Session.GetString("Id"));
            m.DurumTipi = false;
            m.ImageUrl = "~/images/portfolio/image4.jpg";

            switch (MakaleDili)
            {
                case 0:m.MakaleDili = "Turkce"; break;
                case 1:m.MakaleDili = "Ingilizce";break;
                case 2:m.MakaleDili = "Diger";break;
                default:m.MakaleDili = "Turkce";
                    break;
            }
            mb.Makale.Add(m);
            mb.SaveChanges();
            foreach (var cid in catid)
            {
                MakaleKategori mk = new MakaleKategori();
                mk.MakaleId = m.Id;
                mk.KategoriId = cid;
                mk.DurumTipi = true;
                mb.MakaleKategori.Add(mk);
                mb.SaveChanges();
            }
            IEnumerable<Kategori> k = mb.Kategori;

            return View(k);
        }
    }
}

Makalem/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Makalem.Models;
using Microsoft.AspNetCore.Mvc;

namespace Makalem.Controllers
{
    public class SignUpController : Controller
    {
        MakaleAraBulContext mabc = new MakaleAraBulContext();
        [HttpGet]
        public IActionResult SignUp()
        {
            ViewData["pass"] = "";
            return View();
        }
        [HttpPost]
        public IActionResult SignUp(string name,string surname,string email,string username, string password,string confirmpassword,byte usertype)
        {
            if (password.Equals(confirmpassword))
            {

                Kullanici klnc = new Kullanici();
                klnc.Adi = name;
                klnc.Soyadi = surname;
                klnc.Email = email;
                klnc.KullaniciAdi = username;
                klnc.Sifre = password;
                klnc.KullaniciTipi = usertype; // 0-reader  1- writer 2-admin
                klnc.DurumTipi = true;

                mabc.Kullanici.Add(klnc);
                mabc.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else {
                ViewData["pass"]="Şifre ve Şifre Tekrar'ı aynı değil. ";
            }

            return View();

          
        }

    }
}

Makalem/Controllers/SigninController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Makalem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Makalem.Controllers
{
   
    public class SigninController : Controller
    {
        MakaleAraBulContext mabc = new MakaleAraBulContext();
        [HttpGet]
        public ActionResult Signin()
        {
            var klnc = mabc.Kullanici;

            ViewData["info"] = "";
            return View(klnc);
        }

        [HttpPost]
        public ActionResult Signin(string email, string password)
        {

            if (mabc.Kullanici.Where(i => i.Email == email && i.Sifre == password).Any())
            {
                Kullanici giris = mabc.Kullanici.FirstOrDefault(i => i.Email == email && i.Sifre == password);

                HttpContext.Session.SetString("Id",giris.Id.ToString());
                HttpContext.Session.SetString("Adi", giris.Adi.ToString());
                HttpContext.Session.SetString("Soyadi", giris.Soyadi.ToString());
                HttpContext.Session.SetString("Email", giris.Email.ToString());
                HttpContext.Session.SetString("KullaniciAdi", giris.KullaniciAdi.ToString());
                HttpContext.Session.SetString("KullaniciType", giris.KullaniciTipi.ToString());


                
                if (giris.KullaniciTipi == 2)
                {
                    return RedirectToAction("Index", "Admin");
                }
                
                return RedirectToAction("Index", "Home");
            }
            ViewData["info"] = "Yanlış email veya şifre girdiniz !";
            return View();
        }

        public ActionResult SignOut()
        {
            HttpContext.Session.Clear();
                
            return RedirectToAction("Index","Home");
        }

    }
}

Makalem/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/w3.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    

</head>
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
        <h3 class="w3-bar-item">Menu</h3>
        <a class="w3-bar-item w3-button" asp-controller="Admin" asp-action="Usr">Kullanıcılar</a>
        <a class="w3-bar-item w3-button" asp-controller="Admin" asp-action="Article">Makaleler</a>
        <a class="w3-bar-item w3-button" asp-controller="Admin" asp-action="Comment">Yorumlar</a>
        <a class="w3-bar-item w3-button" asp-controller="Home" asp-action="Index">Sisteme Dön</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:25%">

        <div class="w3-container w3-teal">
            <h1>Admin</h1>
            
        </div>

        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>

Makalem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Freelance Photographer PSD Website Template">
    <meta name="keywords" content="HTML,CSS,Bootstrap,JavaScript">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Title -->
    <title>MakaleAraBul</title>

    <!-- Bootstrap CSS and font-awesome -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Main CSS -->
    <link href="~/css/main.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/Signin.css" rel="stylesheet" />
    <link href="~/css/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,500,500i,700" rel="stylesheet">

</head>
<body>
    <!-- Return to Top -->
    <a href="javascript:" id="return-to-top"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
    <!-- Header Section Start -->
    <header>
        <!-- Container Section Start -->
        <div class="container">
            <!-- Row Start -->
            <div class="row">
                <!-- First column Start -->
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <a href="https://www.makalearabul.com" target="_blank"><p>www.makalearabul.com</p></a>
                </div>
                <!-- Second column Start -->
                <div class="col-xs-12 col-sm-4 col-md-4">

                    <a class="logo" asp-controller="Home" asp-action="Index"><img src="~/images/logo/logo.png" alt="logo" width="72" height="66"></a>
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">


                </div>
                <!-- Third column Start -->
                <div class="col-xs-12 col-sm-4 col-md-4" >
                    &nbsp &nbsp  &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
                    @if (Context.Session.GetString("Id") != null)
                    {

                        @if (Context.Session.GetString("KullaniciType") != "0")
                        {
                            <a  style="float:right;"class="btn btn-default" asp-controller="MakaleEkle" asp-action="MakaleEkle">Makale Yaz</a> 
                        }
                        else
                        {
                            <label style="color:white;"> @Context.Session.GetString("KullaniciAdi")</label>

                        }

                        <a   style="float:right; margin-right:5px;" class="btn btn-default" asp-controller="Signin" asp-action="SignOut">Çıkış Yap</a>

                    }
                    else
                    {
                        <a class="btn btn-default" asp-controller="Signin" asp-action="Signin">Giriş Yap </a>
                        <a class="btn btn-default" asp-controller="SignUp" asp-action="SignUp">Kayıt Ol</a>
                    }

                </div>
            </div>
            <!-- Row Ended -->
        </div>
        <!-- Container Section Ended -->
    </header>
    <!-- Header Section Ended -->
    <!-- Navbar Section Start -->
    <nav id="navbar">
        <!-- Container Section Start -->
        <div class="container">
            <!-- navbar-toggle -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <i class="fa fa-bars" aria-hidden="true" style="color:white;"></i>
            </button>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-center">

                    <!--<li><a class="active" href="#">Portraits</a></li>
                     <li class="hidden-xs">-</li>  -->
                    <!-- Eger eklenecek bi sayfa falan olursa burdan ekleyeceğiz -->

                </ul>
            </div>
        </div>
        <!-- Container Section Ended -->
    </nav>
    <!-- Navbar Section Ended -->
    @RenderBody()
    <!-- Footer Section Start -->
    <footer>

        <!-- Footer Links -->
        <div class="container text-md-left">
            <div class="row">

                <!-- First column -->
                <div class="col-sm-6 col-md-3">
                    <a href="index.html"><img src="images/logo/logo.png" alt="logo" width="144" height="144"></a>
                    <p> <span><a href="https://www.makalearabul.com" target="_blank">info@omakalearabul.com</a></span>. Designed by YCNB</p>
                </div>
                <!-- First column -->
                <!--Second column-->
                <div class="col-sm-6 col-md-3 mx-auto">
                    <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">MakaleAraBul</h5>
                    <address>
                        Artık makale araştırmak ve okumak çok kolay. Bir tıkla bilgiye ulaşmanın tadını çıkartın. :) Bize Hızlı Soru bölümünden ulaşabilirsiniz. <br />
                        <br /><a href="https://www.makalearabul.com" target="_blank">info@makalearabul.com</a><br />
                    </address>
                </div>
                <!-- Second column -->
                <!-- Third column -->
                <div class="col-sm-6 col-md-2 mx-auto">
                    <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Site Linkleri</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        @*<li>
                                <a asp-controller="Home" asp-action="About">About Us</a>
                            </li>
                            <li>
                                <a href="Photography.html">Photography</a>
                            </li>*@

                    </ul>
                </div>
                <!-- Third column -->
                <!-- Fourth column -->
                <div class="col-sm-6 col-md-4">
                    <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Hızlı Soru</h5>
                    <form>
                        <ul class="list-unstyled">
                            <li class="row">
                                <div class="col-md-6">
                                    <input required type="text" class="form-control" placeholder="İsim">
                                </div>
                                <div class="col-md-6">
                                    <input required type="text" class="form-control" placeholder="Email">
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-md-12">
                                    <textarea required class="form-control massage" placeholder="Sorunuz.." rows="5" id="comment"></textarea>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-default">Gönder</button>
                                </div>
                            </li>
                        </ul>
                    </form>
                </div>
                <!-- Fourth column -->
            </div>
        </div>
        <!-- Footer Links -->

    </footer>
    <!-- Footer Section Ended -->
    <!-- jQuery (plugins) -->
    <script src="http://code.jquery.com/jquery-1.11.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/javascript.js"></script>
    <script src="~/js/animate.js"></script>
    <script src="~/js/global.js"></script>

</body>
</html>